server:
  port: 8080

security:
  internal-secret: "your-secure-secret-key"
  internal-path-prefix: "/internal/"
  excluded-paths:
    - "/actuator/**"
    - "/health"

  snowflake:
    machine-id: 1

spring:
  autoconfigure:
    exclude:
      - com.intern.hub.library.common.autoconfig.snowflake.SnowflakeAutoConfiguration
      - com.intern.hub.library.common.autoconfig.context.ContextAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/hrm_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # dev: update | prod: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
