[versions]
# Spring
spring-boot = "4.0.2"
spring-cloud = "5.0.1"
dependency-management = "1.1.7"

# Database
postgres = "42.7.9"

# Documentation
springDoc = "3.0.1"

# Code Quality
spotless = "8.1.0"
googleJavaFormat = "1.33.0"

# Mapping & Utils
mapstruct = "1.6.3"
lombok = "1.18.42"
lombok-mapstruct-binding = "0.2.0"
jakarta-validation = "3.0.2"

# Custom Libraries
common-library = "2.0.3"
security-starter = "1.0.3"

[libraries]
# Spring Boot Starters
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-webmvc = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc", version.ref = "spring-boot" }
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security", version.ref = "spring-boot" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-starter-log4j2 = { group = "org.springframework.boot", name = "spring-boot-starter-log4j2", version.ref = "spring-boot" }
spring-boot-starter-liquibase = { group = "org.springframework.boot", name = "spring-boot-starter-liquibase", version.ref = "spring-boot" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "spring-boot" }

# Spring Cloud
spring-cloud-eureka = { group = "org.springframework.cloud", name = "spring-cloud-starter-netflix-eureka-client", version.ref = "spring-cloud" }
spring-cloud-feign = { group = "org.springframework.cloud", name = "spring-cloud-starter-openfeign", version.ref = "spring-cloud" }

# Database
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgres" }

# Documentation
openapi-doc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springDoc" }

# MapStruct
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }

# Lombok
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
lombok-mapstruct-binding = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version.ref = "lombok-mapstruct-binding" }

# Utils
jakarta-validation = { group = "jakarta.validation", name = "jakarta.validation-api", version.ref = "jakarta-validation" }

# Custom Libraries
common-library = { group = "com.github.FPT-IS-Intern", name = "Intern-Hub-Common-Library", version.ref = "common-library" }
security-starter = { group = "com.github.FPT-IS-Intern", name = "Intern-Hub-Security-Starter", version.ref = "security-starter" }

[bundles]
# Spring Boot All: Web + Validation
spring-boot-all = ["spring-boot-starter-webmvc", "spring-boot-starter-validation"]

# Spring Boot Database: JPA + PostgreSQL
spring-boot-database = ["spring-boot-starter-data-jpa", "postgresql"]

# Custom Libraries: Common + Security
custom-libraries = ["common-library", "security-starter"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
